# -*- coding: utf-8 -*-
"""Codigo1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rWkCt2ACTunb7gpZTVjhdTrgCNUeHVup
"""

class ALUMNO():
  Nombre= "Fulanito Perenganito de la Cruz Quintillo"
  Peso="60 kg"
  Edad= 17
  Altura= "1.68 M"
  Sexo= "Masculino"
  Promedio= 8
  def inscripcion(self):
    self.inscrito=True

  def inscrito(self):
    if(self.inscripcion):
      return "El alumno esta inscrito"
    else:
      return "El alumno no esta inscrito"

  def asesorias1(self):
    self.asesoria=True

  def asesorias(self):
    if(self.asesorias1):
      return "El alumno esta en asesorias"
    else:
      return "El alumno no se encuentra en asesorias"

alumno=ALUMNO()

print("El nombre del alumno es: ", alumno.Nombre)
print("El peso del alumno es: ", alumno.Peso)
print("La edad del alumno es: ", alumno.Edad)
print("La altura del alumno es: ", alumno.Altura)
print("El sexo del alumno es: ", alumno.Sexo)
print("El promedio del alumno es: ", alumno.Promedio)

print(alumno.inscrito())
print(alumno.asesorias())