# -*- coding: utf-8 -*-
"""Diccionarios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bsg5-pl1wiJr8i2nZMx8lP9lEkoJE_zA
"""

alumno = {
    "nombre": "Edwin Amitiel Montoya Aguilar",
    "edad": 17,
    "correo": "correoejemplo@gmail.com",
    "peso": "52 kg",
    "telefono": "311338xxxx",
    "domicilio": "Direccion inventada.gogogo",
    "carrera": "Ciencia de Datos e Inteligencia Artificial",
}


print(alumno)
#La instruccion anterior imprime el diccionario completo

print(alumno  ["nombre"])
#La instruccion anterior imprime el nombre del alumno, se utiliza una instruccion similar similar para llamar todos los objetos que estan dentro el diccionario

#Ejemplo:
print(alumno  ["edad"])
print(alumno  ["correo"])
print(alumno  ["peso"])
print(alumno  ["telefono"])
print(alumno  ["domicilio"])
print(alumno  ["carrera"])

#Las instrucciones anteriores pueden ser consideradas como "codigo extra" porque se pueden optimizar para tener menos lineas
#Se recomienda hacer lo anterior (A menos que te paguen por linea de codigo, en ese caso disimula que el codigo esta mas largo de lo que deberia 🗿)

print(" ")
print("Separacion para el diccionario en ciclo for:")
print(" ")
for e in alumno:
  print(alumno[e])


print(" ")
  #Para modificar un objeto dentro de un diccionario se usa:
alumno["nombre"] = "Montoya Aguilar Edwin"
print(alumno["nombre"])