# -*- coding: utf-8 -*-
"""L0CUR4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XyL65rse1sP_p54FX7vmU_dq4hwau1Fx
"""

#EdMA

class alumnado():
  alumnos = []
  calificaciones = []
  promedio_grupal = 0
  alumnos_de_9 = []

  def leer_cal(self):
    print("Ingresa el nombre y calificacion de 10 alumnos:")
    for e in range(10):
      nombre = input("Nombre: ")
      calificacion = float(input("Calificacion: "))
      self.alumnos.append(nombre)
      self.calificaciones.append(calificacion)
      if calificacion > 9.5:
        self.alumnos_de_9.append(nombre)


  def promedio(self):
    total_calificaciones = sum(self.calificaciones)
    self.promedio_grupal = total_calificaciones / len(self.calificaciones)

  def imprimir(self):
    print("El promedio grupal es de: ", self.promedio_grupal)
    if len(self.alumnos_de_9) <= 0:
      print("No hubo alumnos con promedio mayor a 9.5")
    else:
      print("Los alumnos con promedio mayor a 9.5 son: ")
      for e in self.alumnos_de_9:
        print(e)


Estudiantes = alumnado()
Estudiantes.leer_cal()
Estudiantes.promedio()
Estudiantes.imprimir()