# -*- coding: utf-8 -*-
"""temps.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mfY8ZEFEuxko7WyXe26ZE8WhJQOJb28o
"""

#Conversion de temperaturas
#EdMA

temp= [80, 72, 95, 82, 79, 72, 85]

for x in temp:
  celsiu = (x - 32) / 1.8
  count = temp.index(x)
  temp[count] = celsiu

print("las temperaturas convertidas a celsius son las siguientes: ", temp)