# -*- coding: utf-8 -*-
"""tr_area.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FihCcw_sQrsvq1-cv7LVdIdTTZFk45S6
"""

#EDMA

class triangulo():
  base    = 0
  altura  = 0

  def ReadData(self):
    self.base    = float(input("Enter base: "))
    self.altura  = float(input("Enter height: "))

  def area(self):
    return (self.base * self.altura) / 2

  def printData(self):
    print("Area: ", self.area())

triangulo1 = triangulo()
triangulo1.ReadData()
triangulo1.printData()